syntax = "proto3";

package user.v1;

option go_package = "backend-diplomski/proto/gen/user/v1;userv1";

service AuthService {
  rpc SignUp(SignUpRequest) returns (SignUpResponse) {}
  rpc SignIn(SignInRequest) returns (SignInResponse) {}
  rpc SignOut(SignOutRequest) returns (SignOutResponse) {}
  rpc RefreshToken(RefreshTokenRequest) returns (RefreshTokenResponse) {}
  rpc ForgotPassword(ForgotPasswordRequest) returns (ForgotPasswordResponse) {}
  rpc VerifyEmail(VerifyEmailRequest) returns (VerifyEmailResponse);
}

message UserInfo {
  string id = 1;
  string email = 2;
  string username = 3;
}

message SignUpRequest {
  string email = 1;
  string username = 2;
  string password = 3;
  int32 birth_year = 4;
  string gender = 5;
  string country_code = 6;
  string preferred_language = 7;
  repeated string interests = 8;
}

message SignUpResponse {
  string access_token = 1;
  string refresh_token = 2;
  UserInfo user_info = 3;
}

message SignInRequest {
  string identifier = 1;
  string password = 3;
}

message SignInResponse {
  string access_token = 1;
  string refresh_token = 2;
  UserInfo user_info = 3;
}

message ForgotPasswordRequest {
  string email = 1;
  string username = 2;
  string password = 3;
}

message ForgotPasswordResponse {
  string access_token = 1;
  UserInfo user_info = 2;
}

message RefreshTokenRequest {
  string refresh_token = 1;
}

message RefreshTokenResponse {
  string access_token = 1;
  string refresh_token = 2;
}

message SignOutRequest {
  string refresh_token = 1;
}

message SignOutResponse {}

message VerifyEmailRequest {
  string token = 1;
}

message VerifyEmailResponse {
  bool verified = 1;
  string message = 2;
}
