syntax = "proto3";

package user.v1;

option go_package = "backend-diplomski/proto/gen/user/v1;userv1";
option java_multiple_files = true;
option java_outer_classname = "UserProto";
option java_package = "com.example.feeder.proto.user.v1";

service UserService {
  rpc GetCurrentUser(GetCurrentUserRequest) returns (GetCurrentUserResponse) {}
}

message User {
  string id = 1;
  string email = 2;
  string username = 3;
  string created_at = 4;
  string updated_at = 5;
}

message GetCurrentUserRequest {}

message GetCurrentUserResponse {
  User user = 1;
}
